name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        emacs_version: ['29.1', '30.2']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - run: mkdir -p .packages
      - run: git clone --depth 1 https://github.com/purcell/package-lint.git .packages/package-lint
      - run: make test compile checkdoc
      - run: make package-lint EMACS="emacs -L .packages/package-lint"

  gptel-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: '30.2'
      - run: mkdir -p .packages
      - run: git clone --depth 1 --branch v0.9.9.4 https://github.com/karthink/gptel.git .packages/gptel
      - run: emacs -Q --batch -L . -L .packages/gptel -l test/gptel-runner-gptel-test.el -f ert-run-tests-batch-and-exit

  gptel-master-warning:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: '30.2'
      - run: mkdir -p .packages
      - run: git clone --depth 1 https://github.com/karthink/gptel.git .packages/gptel
      - run: emacs -Q --batch -L . -L .packages/gptel -l test/gptel-runner-gptel-test.el -f ert-run-tests-batch-and-exit
